/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assign2;

import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 */
public class RTrip extends javax.swing.JFrame {
      Internal f= new Internal();    
    Customer c=new Customer();
    IntScreen intsc=new IntScreen();
     int x,z;    
    public ArrayList<Internal> intern= new ArrayList<>();
    public ArrayList<Internal> displayedlist = new ArrayList<>();

    /**
     * Creates new form RTrip
     */
    public RTrip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Trip's code      -Method of transportation       -Number of stops      -Date" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Tap to begin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Confirm Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("If there're no suitable trips please exit.");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Files f =new Files();
        try {
            intern=f.Readintern();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IntScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<intern.size();i++)
        {
            Internal t;
            t=intern.get(i);
            if(t.getCurrentloc().equalsIgnoreCase(intsc.destination)&& t.getDestination().
                equalsIgnoreCase(intsc.currentlocation))
            {
                displayedlist.add(t);
            }
        }
        String text;
        //jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(displayedlist.toArray));
        for (int i=0;i<displayedlist.size(); i++){
            text=displayedlist.get(i).getNooftrip()+",            "
            +displayedlist.get(i).getMethodoftrans()+",                                       "
            +displayedlist.get(i).getNoofStops()+",                            "
            +displayedlist.get(i).getTraveldate();
            jComboBox4.addItem(text);
        }

        // TODO add your handling code here:
        //        c.setName(extsc.name);
        //        c.setAge(extsc.age);
        //
        //        if(extern.get(x).getNoofavab()>=extsc.y){
            //        c.setNoofBooked(extsc.y);
            //        String n=extern.get(x).getNooftrip();
            //        double t=extern.get(x).getPrice();
            //        c.setTprice(t*0.5);
            //        c.setCodet(n);
            //        Files f= new Files();
            //        try {
                //            f.Appendcust(c);
                //        } catch (IOException ex) {
                //            Logger.getLogger(ExtScreen.class.getName()).log(Level.SEVERE, null, ex);
                //        }
            //        z= extern.get(x).getNoofavab();
            //        z=z-c.noofBooked;
            //        extern.get(x).setNoofavab(z);
            //
            //
            //Files f1= new Files();
            //            try {
                //
                //               f1.Appendextern(extern);
                //            } catch (IOException ex) {
                //                Logger.getLogger(ExtScreen.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //        }
        //        else
        //        {JOptionPane.showMessageDialog(rootPane, "No seats available.");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String   choice[]=jComboBox4.getSelectedItem().toString().trim().split(",");
        for(int i=0;i<intern.size();i++)
        {
            if(choice[0].equals(intern.get(i).getNooftrip()))
            {
                x=i;
            }

        }
        c.setName(intsc.name);
        c.setAge(intsc.age);

        if(intern.get(x).getNoofavab()>=intsc.y){
            c.setNoofBooked(intsc.y);
            String n=intern.get(x).getNooftrip();
            double t=intern.get(x).getPrice();
            c.setTprice(f.discount(t));
            double totalprice= f.discount(t)+t;
            c.setCodet(n);
            Files f= new Files();
            try {
                f.Appendcust(c);
            } catch (IOException ex) {
                Logger.getLogger(ExtScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            z= intern.get(x).getNoofavab();
            z=z-c.noofBooked;
            intern.get(x).setNoofavab(z);

            Files f1= new Files();
            try {

                f1.Appendintern(intern);
            } catch (IOException ex) {
                Logger.getLogger(IntScreen.class.getName()).log(Level.SEVERE, null, ex);
            }        JOptionPane.showMessageDialog(rootPane, "Booking confirmed! Your whole trip will cost:  "+totalprice+".  For more information call 19999");

        }
        else JOptionPane.showMessageDialog(rootPane,"No seats avaliable:");
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane, "No seats available.");}
//
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        exit(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RTrip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
